version: '2.1'
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node
      - image: circleci/mongo:4.1.9
    steps:
      - checkout
      # check cache if exists
      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - node/install-packages
      - save_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - package-lock.json
      - run:
          name: 'seed db'
          command: npm run seed
      - run:
          name: 'Run tests with npm'
          command: npm run test
  lint: 
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - node/install-packages
      - save_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - package-lock.json
      - run:
          name: 'linting'
          command: npm run lint
workflows:
  run-unit-tests:
    jobs:
      - lint
      - test
          
