version: '2.1'
orbs:
  node: circleci/node@4.1.0
  slack: circleci/slack@4.1
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: 'Run tests with npm'
          command: npm run test
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  send-notification:
    jobs:
      - test
      - notify:
          context: Slack
